name: memory-mesh
region: nyc

services:
  - name: api
    github:
      repo: shubhhh19/memory-layer
      branch: main
      deploy_on_push: true
    
    source_dir: /
    build_command: pip install --upgrade pip && pip install uv && uv sync --frozen --no-dev && alembic upgrade head
    run_command: .venv/bin/uvicorn ai_memory_layer.main:app --host 0.0.0.0 --port ${PORT:-8080}
    
    environment_slug: python
    python_version: "3.12"
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    health_check:
      http_path: /v1/admin/health
    
    envs:
      - key: MEMORY_ENVIRONMENT
        value: production
        scope: RUN_TIME
      - key: MEMORY_SQL_ECHO
        value: "false"
        scope: RUN_TIME
      - key: MEMORY_ENABLE_METRICS
        value: "true"
        scope: RUN_TIME
      - key: MEMORY_ASYNC_EMBEDDINGS
        value: "true"
        scope: RUN_TIME
      - key: MEMORY_GLOBAL_RATE_LIMIT
        value: "200/minute"
        scope: RUN_TIME
      - key: MEMORY_TENANT_RATE_LIMIT
        value: "120/minute"
        scope: RUN_TIME
      - key: MEMORY_DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET
      - key: MEMORY_REDIS_URL
        value: ${redis.REDIS_URL}
        scope: RUN_TIME
        type: SECRET
      - key: MEMORY_JWT_SECRET_KEY
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: MEMORY_ALLOWED_ORIGINS
        value: ""
        scope: RUN_TIME
        type: SECRET
    
    routes:
      - path: /

  - name: frontend
    github:
      repo: shubhhh19/memory-layer
      branch: main
      deploy_on_push: true
    
    source_dir: frontend
    build_command: npm install && npm run build
    run_command: npm start
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 3000
    
    envs:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: ${api.PUBLIC_URL}
        scope: RUN_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    db_name: memory_layer
    db_user: memory
  
  - name: redis
    engine: REDIS
    version: "7"
    production: false

